export const SKILLS_FETCHED = 'SKILLS_FETCHED';
export const SKILL_POSTED = 'SKILL_POSTED';
export const DELETE_PUSHED = 'DELETE_PUSHED';
export const SKILL_REMOVED = 'SKILL_REMOVED';
export const ACCOUNT_SAVE_SUCCESS = 'ACCOUNT_SAVE_SUCCESS';
export const LOAD_TEST_SKILL = 'LOAD_TEST_SKILL';
